import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import '../../lang/lang.dart';
import '../../theme/app_theme.dart';
import 'privacy_policy_logic.dart';

class PrivacyPolicyView extends GetView<PrivacyPolicyLogic> {
  const PrivacyPolicyView({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        leading: IconButton(icon: Icon(Icons.arrow_back_ios), onPressed: () => Get.back()),
        title: Text(Lang.privacy, style: TextStyle(fontSize: ScreenUtil().setSp(18), fontWeight: FontWeight.w600)),
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.all(ScreenUtil().setWidth(16)),
        child: Text(
          _content,
          style: TextStyle(fontSize: ScreenUtil().setSp(14), color: theme.colorScheme.onSurface, height: 1.6),
        ),
      ),
    );
  }

  static const String _content = '''
Last Film Privacy Policy

Last Updated: 2025

1. Introduction

Last Film ("we", "our", or "the app") is a film simulation camera application that operates entirely on your device. We are committed to protecting your privacy. This Privacy Policy explains how we handle information when you use our app.

2. Data Collection

Last Film does NOT collect, transmit, or store any personal data on external servers. All data generated by the app, including:
- Photos you capture
- Film roll settings and preferences
- App configuration and settings

is stored locally on your device only.

3. Local Storage

All data is stored in your device's local storage (SQLite database and file system). We do not have access to this data. You can delete all app data by uninstalling the application.

4. No Network Requests

The app is designed to work completely offline. It does not make any network requests, does not connect to the internet, and does not transmit any information to third parties.

5. Permissions

The app may request the following permissions:
- Camera: To capture photos
- Photo Library: To save and access photos you create with the app

These permissions are used only for the stated purposes and no data is shared externally.

6. Children's Privacy

Our app does not knowingly collect any personal information from children. The app is suitable for all ages as it does not collect or transmit user data.

7. Changes to This Policy

We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy in the app. You are advised to review this policy periodically.

8. Contact Us

If you have any questions about this Privacy Policy, please contact us through the app settings.
''';
}
